---
abstract: 'open, read and seek into remote files and directories transparently'
author:
  - 'Thomas Drugeon, <tdrugeon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-HTTP
no_index:
  directory:
    - inc
    - t
recommends:
  IO::Socket::SSL: 0
  Time::y2038: 0
requires:
  constant: 1.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.91
